### ISSUE TITLE
Créer une page de connexion

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#10]

**Comment by baptistebisson** [comment]
Problème compilation SCSS avec laravel

**Comment by baptistebisson** [comment]
Ton identifiant : cham@gmail.com
Mot de passe : chamseddine

User générique : user@mail.fr
Mot de passe motdepasse

**Comment by ChamMach** [comment]
Excellent ! Y'a-t-il un système d'envoi d'e-mail ? Car sinon on aura du mal à justifier lors de la soutenance l'utilisation d'une adresse e-mail. Sinon c'est super, on ferma les issues début janvier lorsqu'on sera en groupe. Enfin, n'oublie pas de mettre à jour le tableau kanban : 
 https://github.com/ChamMach/VirtualWeb/projects/2

Si tu penses qu'une issue est achevée ou en cours, déplace-la simplement dans la colonne adéquate (cela me permettra de mettre à jour le fichier Excel) :)

**Comment by baptistebisson** [comment]
Non pas pour l'instant. Mais ça n'empêche pas de garder ce champ pour le moment je pense.

Pas de problème !
