### ISSUE TITLE
Créer une page de visualisation des VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#11]
- Visualisation de la totalité des VM d'un utilisateur
- Visualisation de l'état des VM (hors ligne/ en ligne)

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/c954b6ee92877d83740a8cfbd19bb912b1006250 Les données viennent désormais de la BDD.
Il faudra par la suite lancer une tache cron sur le kernel afin d'update la BDD toutes les minutes.

Actuellement, sous Windows tu peux utiliser mon script `taskerForWindows.bat`
```
:loop
php artisan schedule:run 1>> NUL 2>&1
sleep 60
goto loop
```
Il s'agit d'une boucle qui se lance toutes les minutes pour exécuter la commande.

**Comment by ChamMach** [comment]
Cette commande exécute quoi exactement ? Je ne comprends pas vraiment comment elle appelle le script python. Sauf si au préalable tu as fait un script permettant d'être appelé avec cette commande. Je créerais son équivalent linux lorsque je testerais les dernières versions du site.

J'ai ajouté le type "all" pour les fonctions listing_vm et infos_vm, tu peux donc utiliser ces fonctions pour avoir des infos sur un utilisateur ou la totalité. De plus un readme à été ajouté : https://github.com/ChamMach/VirtualWeb/tree/mvp1/PythonScripts 

Je l'étofferais au fur et à mesure du temps et des fonctions crées 👍

**Comment by baptistebisson** [comment]
https://laravel.com/docs/5.5/scheduling
> When using the scheduler, you only need to add the following Cron entry to your server. If you do not know how to add Cron entries to your server, consider using a service such as Laravel Forge which can manage the Cron entries for you:
> 
> php /path-to-your-project/artisan schedule:run >> /dev/null 2>&1
> This Cron will call the Laravel command scheduler every minute. When the schedule:run command is executed, Laravel will evaluate your scheduled tasks and runs the tasks that are due.

Parfait !

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/7a894eb446601ac6b470f282837486f0916c2157 : 
- Le script d'automatisation utilise la commande `infos_vm: all`, ainsi toutes les vm sont mises à jour
- Utilisation des variables du fichier d'environnement pour adapter la configuration de connexion au script selon l'environnement de l'utilisateur. (voir fichier `.env` section `SCRIPT_VM_IP` et `SCRIPT_VM_PORT`

**Comment by ChamMach** [comment]
Thx pour ces infos !

Néanmoins il semblerait que je ne puisse pas récupérer les infos remontées par le script. Ceux-ci sont bien remontés : 

![image](https://user-images.githubusercontent.com/23166349/34694897-0118fd32-f4c9-11e7-8a1d-fc2cf28b00d0.png)

Mais ils ne sont pas présents dans la table vm, ni dans la vue "Virtuals Machines" pour chacun des users : 
![image](https://user-images.githubusercontent.com/23166349/34695302-a201a842-f4ca-11e7-840d-3e19e78e6e29.png)

J'utilise une version du script python (commit : e9f92e257673606f0b1a922fcfe4630f9a0f884c) , prenant en compte une adresse IP de notre machine. J'ai de plus modifié le fichier .env (ajout de : 
SCRIPT_VM_IP=192.168.1.11
SCRIPT_VM_PORT=1333 
par exemple) mais cela ne semble pas fonctionner. Une idée ? 
Je suis en train de bosser sur la création de vm, la suppression ainsi que le démarrage. Je mettrais à jour le git dans les jours qui viennent sur ces différents sujets :)
