### ISSUE TITLE
Créer la page d'accueil

### ISSUE THREAD

**Issue by baptistebisson** [ChamMach/VirtualWeb#12]
Page qui regroupe la structure : 

- Sidebar
- Header
- Content

Accessible uniquement si utilisateur connecté via le formulaire de connexion #10

**Comment by baptistebisson** [comment]
Gestion de la page d'accueil : 

- Affichage des VM dans une card (statique pour le moment)

Ce commit comprend en plus une meilleure gestion de la page de connexion. Mise en place du style de la sidebar et du header.
La sidebar affichera le nom & prénom de la personne et les différents liens (@ChamMach j'aurais besoin de ton avis sur ce qu'il faudra dedans).

**Comment by ChamMach** [comment]
Possibilité de partager une ou plusieurs images du rendu ? 

Excellent boulot en tout cas. Le fait est que sur cette page d'accueil je pense que tu peux l'organiser comme bon te semble. À mon avis il faudrait que l'on puisse au moins voir la liste des VMs et leurs états (en ligne/hors-ligne avec pourquoi pas une led verte/rouge). Puis pourquoi pas une partie dédiée aux conteneurs Docker associés à une VM dans une prochaine MVP. Tout dépend si cette page d'accueil rentre ou non dans l'idée des issues #11 #2 et #3 (ce qui ferais doublon).

Pour la sidebar en effet le nom, le prénom et des liens du style "déconnexion" ou des informations sur le nombre de VM/conteneurs actifs/hors-lignes, etc. 
À voir si l'on souhaite aussi tout faire depuis la page d'accueil (création d'une vm, création d'un conteneur, etc) et si l'on souhaite suivre à 100% les diagrammes UML que j'ai créé : https://drive.google.com/drive/folders/1hRnSGQdu590fzsCDuIARorkh8MfiaT3z

Personnellement, j'avais comme idée de tout faire depuis les listes des VM/conteneurs (avec des boutons et des "popup"/pages apparaissant. Mais encore une fois tout dépend de la complexité et du temps nécessaire à ces réalisations. La sidebar pourrait du coup mettre en avant la création de VM/conteneurs.

**Comment by baptistebisson** [comment]
Page de login : 
![Login page](https://i.imgur.com/n2bERwC.png)
Gestion des erreurs : 
![Login page erreur](https://i.imgur.com/o4u122D.png)
Début de page d'accueil : 
![Page d'accueil](https://i.imgur.com/vPUgFD8.png)
La couleur du login va changer pour prendre celle de l'accueil je pense.

Je peux tout faire depuis cette page d'accueil. J'utilise un routeur de vue-js qui me permet cela justement et les requêtes se feront en ajax (directement à ton ip) pour remplir mes données.
Tu peux déjà voir sur la page d'accueil la card d'une VM. J'ai juste oublié de mettre le nom de la VM mais tu vois le système.

1. Onglet infos général sur la VM
2. Caractéristiques de la VM
3. Actions

Après on peut aussi imaginer une modale qui s'ouvre pour gérer ça avec plus d'espace.

**Comment by ChamMach** [comment]
C'est excellent ! L'onglet "mes machines" ne serait pas redondant avec ce que l'on peut voir dans l'accueil ? Ou alors cela fera "apparaître" des fonctionnalités supplémentaires (du genre tri des vms par nom, etc) ? Dans le cas où il y aurait énormément de machines, je pense du coup que l'accueil devrait montrer sur une ligne ou deux des vms (mises en favoris dans "mes machines" ?) ainsi que des conteneurs (2-3 favoris dans "mes conteneurs" ?). Qu'en penses-tu ? Cela est faisable ou cela prendrait trop de temps/modifications (car j'imagine que l'idée des favoris ferait intervenir une ou plusieurs tables supplémentaires ...). En tout cas, gros gg à toi Baptiste ! 👍

**Comment by baptistebisson** [comment]
Merci bien 👍 Oui en fait c'était surtout pour remplir un peu la sidebar. C'est faisable oui mais il faudra voir ça dans la mvp2 je pense.

**Comment by baptistebisson** [comment]
Ajout : 

- Système de contenu dynamique. Un clic sur un lien de la sidebar ne nécessite pas un rechargement de la page. Fluidité accrue car aucun temps de chargement.
