### ISSUE TITLE
Créer une page d'administration

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#13]
_À compléter (page regroupant les fonctions d'ajout/suppression/modification d'un utilisateur)._

**Comment by baptistebisson** [comment]
Commit #2425a1d : 

- Page administration
- Ajout utilisateur (vérification sur l'email)
- Suppression utilisateur (vérification si existe)
- Ajout d'un système de notification
- Meilleur séparation user/admin
- Ajout middleware **isAdmin** et **isUser**
