### ISSUE TITLE
Créer une page montrant les caractéristiques d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#14]
À compléter

**Comment by baptistebisson** [comment]
Commit #3783a80 : 

- Mise en place du système dynamique d'affichage des VM (pour le moment la donnée vient d'un array définit à la main en base, il s'agira par la suite de faire appel au script python)
- Ajout des onglets `Détails` et `Options`
- Ajout d'un libellé permettant de voir facilement si la VM est `on` ou `off`

@ChamMach Penses-tu qu'il est indispensable de récupérer en permanence les données via ton script ? Ne serait-il pas plus facile de tout stocker en base, et faire appel au script automatiquement toutes les 5 min si aucune activité de l'utilisateur n’a eu lieu ? (ex : création d'une vm)

Ca réduirait la charge, le délai de réponse etc ... Il s'agira ensuite de faire un maintien de la base régulièrement via des `update`

Sans ça le système de filtre ne peut pas avoir lieu (ex du favoris).

**Comment by ChamMach** [comment]
Si nous stockons les données et les rafraîchissons toutes les 5 minutes via n'importe quelle méthode, il y a un risque pour que les données à M+5 soient complètement différentes. Pour notre besoin de visualisation des informations, ce n'est pas très grave, à voir si cela influencera la création de vm ou autre. 
Cela signifie un travail supplémentaire et qui dépend surtout de ce que tu veux dire lorsque tu dis "tout en base". Mais l'idée est bonne et applicable, je pense.

**Comment by baptistebisson** [comment]
Et d'après toi, quels éléments peuvent changer entre ces 5 minutes si l'utilisateur ne fait rien ?

**Comment by ChamMach** [comment]
Et bien tout dépend si la VM est en activité ou non. Mais comme je te l'ai dit, cela dépend aussi de ce que tu veux mettre en bdd.
