### ISSUE TITLE
Script VM - Partie visualisation des caractéristiques d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#15]
Caractéristiques retournées par le script : 

- Description de la VM (qui sera obligatoire lors de sa création)
- Type d'OS (Windows 7, Linux ...)
- Nombre de CPU 
- Taille de la mémoire vive (en Mo)
- Nombre de disque dur et taille allouée

**Comment by ChamMach** [comment]
Commit :  f7c9808
Ajout des fonctions infosvm et convert.
Fonctionnalité testée : Récupération des caractéristiques des vm d'un utilisateur 
Retour json : 


{
	"infos_vm": "idUtilisateur",
	"vm_1": {
		"nom": "xxx",
		"desc": "xxx", **(decription de la vm, que l'on rendra obligatoire à la création (pouvant ainsi être dans l'espace "Lorem Ipsum" de la VM sur le site web)**
		"cpu": "xxx",
		"ram": ["nb","unite"], **(unité = Mo/Go/To)**
		"os": "xxx", **(type d'OS présent sur la VM. Exemple : Windows7_64 pour Windows 7 64 bits. Je ne pense pas que ce serait utile de "changer" le ce retour à l'affichage puisqu'il y a énormément de variante possible)**
		"sto_l": ["nb","unite"], **(unité = octects/Ko/Mo/Go/To)**
		"sto_r": ["nb","unite"] **(unité =  octects/Ko/Mo/Go/To)**
		},
	"vm_2": { ... }
}

Le stockage logique correspond au stockage total alloué à la vm (peux importe le nombre de disques durs). Le stockage réel est le stockage effectivement utilisé par la vm. Si le stockage logique est en mode "taille dynamique" (ce qui est le cas par défaut), le stockage réel augmentera au fur et à mesure de l'utilisation de la VM. En revanche, si le stockage logique est en mode "taille fixe" alors le stockage réel sera égal au stockage logique (puisqu'il prend effectivement tout l'espace qu'on lui a alloué).

Code php employé : 
```
<?php require_once('D:\wamp64\www\virtualweb\shelpher.php');

#$sockethelper = new sockethelper('172.31.0.85',1333);

$sockethelper = new sockethelper('192.168.1.11',1333);
$test = array(
    'infos_vm' => "123");
$string = json_encode($test);

$sockethelper->send_data($string);

var_dump($sockethelper->read_data());

$sockethelper->close_socket();

?>
```
123 = idUtilisateur
nombre de vm associé à cet utilisateur : 3.

Le retour json envoyé par le code python : 
```
"{"infos_vm": "123", "vm_1": {"nom": "123_test", "desc": "test vm 1 2 3", "os": "Windows7_64", "cpu": 1, "ram": [2, "Go"], "sto_l": [25, "Go"], "sto_r": [2, "Mo"]}, "vm_2": {"nom": "123_test2", "desc": "VM Redhat", "os": "RedHat", "cpu": 1, "ram": [2, "Go"], "sto_l": [25, "Go"], "sto_r": [2, "Mo"]}, "vm_3": {"nom": "123_test3", "desc": " VM MacOS X 10.6 Snow Leopard 32 Bits", "os": "MacOS106", "cpu": 1, "ram": [2, "Go"], "sto_l": [25, "Go"], "sto_r": [2, "Mo"]}}"`
```

On remarque donc que les 3 VM ont des caractéristiques identiques hormis au niveau du nom, de la description ou encore de l'os.

Des questions ou remarques @baptistebisson ?

**Comment by baptistebisson** [comment]
Ca me semble parfait ! Je vais utiliser ce retour JSON pour mon code.

**Comment by baptistebisson** [comment]
Le problème est qu'il me faudra ce retour + le retour de #8 avec comme id le nom de la VM puis un merge des 2 pour mon affichage sur la page d'accueil.

En gros pour faire simple, le même retour JSON avec le statut de la VM

**Comment by ChamMach** [comment]
Ça marche. J'ajouterais donc le statut de la VM dans les caractéristique renvoyés.
Cela sera de la forme : 
"statut": "xxx", (on/off)

**Comment by ChamMach** [comment]
Commit : 640aec9
Suppression de la fonction statevm pour ajout du statut de la vm dans la fonction infosvm
Fonctionnalité testée : Récupération des caractéristiques des vm d'un utilisateur + statut de la vm
Retour json : 
{
"infos_vm": "idUtilisateur",
"vm_1": {
"nom": "xxx",
"desc": "xxx",
"statut": "xxx", **(xxx = on/off/inconnu)**
"cpu": "xxx",
"ram": ["nb","unite"], 
"os": "xxx", 
"sto_l": ["nb","unite"],
"sto_r": ["nb","unite"]
},
"vm_2": { ... }
}
