### ISSUE TITLE
Créer une page permettant la création d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#17]

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/7e2d6ea791f134680d9e0d2c1b7b2f46a5b386f4 J'ai avancé la modal de création d'un VM.

- Ajout d'un pattern à l'input afin d'interdire certains symboles dans le nom d'un VM, notamment le `_`
- Ajout d'un textarea
- Ajout du slider pour le CPU

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/6ba4637cde6ff0340181df6cc97e15f26c783a28 : Il est désormais possible de créer une VM par la modal. Pour le moment par contre il ne faut pas toucher aux valeurs de ram/cpu car j'ai le message d'erreur : `false_modifyvmfailed` à chaque fois.

Je comprends pas trop pourquoi parce que sans rien toucher ça marche.

To do : 
- Actualiser les données de la page si création
- Fermer le formulaire automatiquement

**Comment by ChamMach** [comment]
Parfait ! Pour la ram/cpu, tu envoi bien un integer et pas de valeurs entre guillemets/quotes ? Aussi, il faut indiquer une valeur que ton ordinateur peut supporter (si tu met 21638Go de ram je pense que ça ne fonctionnera pas).

**Comment by ChamMach** [comment]
Plop, je viens de tester la nouvelle fonction de création de VM depuis l'interface web et j'ai deux points à soulever.

- Lorsqu'on n’a aucune VM de disponible pour un utilisateur, il est impossible de créer une VM (on clique sur le bouton, mais rien ne s'affiche) : 
![image](https://user-images.githubusercontent.com/23166349/35182393-38c13790-fdd4-11e7-91f1-6620932c7504.png)


- Sinon, lorsque l'on crée une VM il y a parfois un message disant "un problème est survenu" alors que la VM est en cours de création. Le problème "false_modifyvmfailed" vient du fait que les valeurs pour ram et stockage sont en string (entre guillemets) et pas en integer (comme le cpu) : 

![image](https://user-images.githubusercontent.com/23166349/35182373-d8c40db8-fdd3-11e7-9cc2-cc5fedc9b732.png)

Je déconseille aussi de mettre des valeurs (cpu, ram, stockage) inférieures aux valeurs par défaut que j'ai indiqué ici : https://github.com/ChamMach/VirtualWeb/issues/21 

Cela pourrait résulter d'un problème lors du clonage de la VM (ou de l'allumage). Bon boulot sinon, comme d'hab !

**Comment by baptistebisson** [comment]
Corrigé dans le prochain commit. J'ai forcé le format en integer et j'ai le bon retour !

C'était déjà fais le minimum pour le stockage. Regarde quand tu switch d'os. J'avais pas vu pour la ram par contre.
