### ISSUE TITLE
Créer une page permettant la suppression d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#18]

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/3dd7e4b4aac4d939d2fe14364b27e3592ed3250f : Fonctionnalité basée sur l'allumage/extinction VM.

:warning: Il faudra mettre à jour la BDD pour les seeds

**Comment by ChamMach** [comment]
Parfait, je prends note et testerais ça ce week-end 👍

**Comment by ChamMach** [comment]
Plop, je viens de tester pour le fun la suppression d'une VM qui étais en ligne : 

On reste sur  : 
![image](https://user-images.githubusercontent.com/23166349/35182268-9cd4a7ce-fdd1-11e7-9a41-6a7710c3df4d.png)

Et bien évidemment le retour json est  : 
{"modify_vm": "false_vmonline"}

Du coup, serait-il possible d’empêcher la suppression d'une VM lorsque celle-ci est en ligne ? En grisant le bouton par exemple ? Faire de même aussi pour la modification d'une VM, si possible. Sinon, ça fonctionne super bien 👍

**Comment by baptistebisson** [comment]
Corrigé dans un prochain commit. Les boutons seront désactivés aussi pour allumer et éteindre.
