### ISSUE TITLE
Créer une page permettant la modification d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#19]

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/1f4832e65cee5cb698c80cb4ccc5716e16f9b733 : J'ai ajouté une modal comme celle de la création d'une VM.

Le problème est au niveau des sliders car si on a un stockage avec des décimales, ça foire le slider. Pareil pour le step, si j'ai 100 et que ma VM a 6mo de stockage, tu vois le problème qui peut arriver.

Je pense qu'il faudra simplement faire un test : 
- Si stockage existant en dessous des 25 000 pour WI7
- Remplacer la valeur par celle ci

**To do :** 
- Gérer le backend de cette commande

**Comment by ChamMach** [comment]
Je vois, mais attention, on ne modifie pas le stockage à la baisse. On l'augmente uniquement. 👍 

Et je ne comprends pas le "Si stockage existant en dessous des 25 000 pour WI7" les 25600Mo sont uniquement "utile" à la création, car par défaut aucune VM Win7 ne devrait avoir un stockage en dessous (idem du coup pour les modifications). Néanmoins pour tes tests tu peux prendre en compte un stockage inférieur, mais la VM d'origine (utilisé pour le clonage) a un stockage de 25Go en taille dynamique (7Go "vraiment" clonés lors du processus de création d'une VM sous Windows 7).

**Comment by ChamMach** [comment]
Plop, je viens de tester la nouvelle version du site web. Plusieurs petits points : 

- La ram envoyée et affichée dans l'interface web n'est pas la bonne. En effet, il n'y a pas de conversion Go/Mo lorsqu'on a plusieurs Go de RAM (s'il y a 2Go par exemple, il faut les convertir en Mo (2x1024) avant de les envoyer au programme python)

- Le problème que tu as avec le stockage n'est pas bien méchant, il faut simplement enlever le lecteur optique (symbolisé par un CD) et ça fonctionne : 
![image](https://user-images.githubusercontent.com/23166349/35236086-5d873ac4-ffa6-11e7-93ff-83644f5a93b2.png)

J'imagine que tu n'as pas créé cette VM avec le site web (car il clone une VM qui n'a pas lecteur CD) (ou alors que ta VM 0_Windows7 dispose de ce lecteur) donc ça explique le souci (on n’en a pas besoin pour notre projet). Sinon la modification fonctionne très bien. N'hésite pas à me faire un retour ! 👍

**Comment by baptistebisson** [comment]
https://github.com/ChamMach/VirtualWeb/commit/8d383bb450ac34d80a7feeebf044a59862daf4d4 En effet ça marche mieux en MO 🌮 
Pour le stockage aussi, c'était ce disque qui posait problème !

**Comment by ChamMach** [comment]
Super ! J'ai tout testé et ça fonctionne bien.
En revanche quand une VM est allumée il y a le bouton "modifier" qui n'est pas grisé (il le devrait, car on ne peut modifier une VM que lorsqu'elle est éteinte) : 
![image](https://user-images.githubusercontent.com/23166349/35244697-5e1aae9c-ffc1-11e7-9da1-deff74c2eb16.png)
