### ISSUE TITLE
 Script VM - Partie création d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#21]
Definition of done : 

- [x] Création d'une VM à partir d'un template (Windows7/Centos)

**Comment by ChamMach** [comment]
Commit : a147b71
Ajout de la fonction "createvm" et des fonctions associées (clonevm,modifyvm,vmfind,convertmegaoctetstobytes)
Fonctionnalité testée : Création d'une VM à partir d'un template

Fonctionnement de la fonction crée :  
Le programme python crée une VM à partir d'un template (0_Windows7 pour Windows 7 64 bits, 0_Centos pour une Centos/RedHat 64 bits). Template qui est créé au préalable de façon manuelle sur VirtualBox (avec l'OS d'installé ou non, cela n'a pas d'importance pour l'instant). Le programme modifie les valeurs par défaut du template avec les valeurs envoyées par le code php (Cpu, Ram, Stockage, Nom ...) et enregistre la nouvelle VM dans VirtualBox afin qu'elle soit utilisée pleinement. Le programme ne supporte pour le moment que la création d'une VM Windows7 et une VM Centos/RedHat (simplifié en Centos pour la suite).

Exemple de code php employé pour la création d'une VM sous Windows 7 : 
```
<?php require_once('D:\wamp64\www\virtualweb\shelpher.php');
$sockethelper = new sockethelper('192.168.1.11','1333');
$test = array(
    'create_vm' => "1_Windows7",
    'os' => "Windows7_64",
    'ram' => 2048,
    'cpu' => 2,
    'sto' => 30720,
    'desc' => 'Ceci est une VM Windows7');
$string = json_encode($test);

$sockethelper->send_data($string);

var_dump($sockethelper->read_data());

$sockethelper->close_socket();

?>
```
Ici, le code php va interroger le programme python sur la création d'une VM de type Windows7 64 bits avec des caractéristiques propres. Voici les caractéristiques présentées en détail : 

**nom :** Nom de la VM précédé de l'id de l'utilisateur
**os :** Windows7_64 pour une VM Windows7. RedHat_64 pour une VM Centos/RedHat
**ram :** Quantité de mémoire vive allouée. En Mo. (par défaut 2048Mo, soit 2Go pour une Windows 7. Et, 1024Mo soit 1Go pour une Centos)
**cpu :** Nombre de CPU alloués à la VM (Par défaut 1Cpu pour une Windows 7 et une Centos)
**sto :** Quantité de stockage alloué à la VM (Par défaut 25600Mo soit 25Go pour une Windows 7, 8192Mo soit 8Go pour une Centos). Il faut savoir que la quantité de stockage indiquée ici est le stockage logique de la VM sur un disque (et un seul, car nous travaillons pour le moment que sur un seul disque pour la VM). Ce qui signifie que puisque les VM sont créés en mode de stockage dynamique, les 25Go d'une Windows 7 ne sont pas pris sur le disque hôte du PC/serveur directement, mais progressivement au fur et à mesure de l'utilisation du stockage sur la VM.
**desc :** Description de la VM (par défaut aucune description pour une Windows 7 et une Centos).

Les valeurs par défaut indiquent les valeurs utilisées pour les templates créés sous VirtualBox. Ces valeurs ne peuvent être changées afin de garder une certaine cohérence. Ainsi, j'aimerais savoir @baptistebisson s'il est possible que lorsque l'on a la possibilité de créer une VM, on est le choix uniquement entre Windows 7 et Centos. Et, qu'en choisissant l'un ou l'autre, qu'on ne puisse pas aller en dessous des valeurs par défaut indiquées ci-dessus.

Passons enfin aux code retour json de la fonction create_vm : 
- {"create_vm": "true"} lorsque la VM a été créée correctement
- {"create_vm": "false_modifyvmfailed"} lorsque les modifications du clone de la VM (modification RAM par rapport à la VM template par exemple) ont échoués pour X raisons
- {"create_vm": "false_cloningfailded"} lorsque le clonage de la VM template a échouée
- {"create_vm": "false_osunknown"} lorsque l'OS demandé par le code php n'est pas supporté
- {"create_vm": "false_vmalreadyexist"} lorsque la VM à créer existe déjà (normalement supporté dans le code php mais sécurité supplémentaire ici aussi)


Tu peux tester le programme et la fonction create_vm en créant deux VM dans virtualbox (sans installer d'OS) appelés "0_Windows7" et "0_Centos".  A la création de ces VM, tu n'as qu'à cliquer sur "Suivant" à chaque fois puisque les valeurs par défaut indiqués par virtualbox sont les valeurs par défaut que j'ai indiqués plus haut dans ce poste. Après cela, tu peux lancer l'exe et l'interroger avec le code php que j'ai indiqué (en remplaçant l'OS par RedHat_64 si voulu) et tu remarqueras que la VM a été créée avec les valeurs que tu auras indiquées dans le code php.

Pour ma part j'ai aussi testé avec un OS Windows 7 installé sur ma machine "0_Windows7", le clonage prend un certain temps (plusieurs minutes, car il faut cloner environ 7Go de donnés) mais la VM créée à partir de ce clonage fonctionne bien (en revanche le stockage ne ce met pas automatiquement à jour dans Windows ni dans Linux donc il faudra prévoir un message d'avertissement sur l'interface web @baptistebisson, qui prévient que si l'utilisateur change les valeurs par défaut à la création/modification (pour plus tard), il faudra qu'il étende le disque dans la VM). 

Le seul hic, c'est que lors d'un clonage et suivant la quantité de données à cloner, il n'est pas possible de faire d'autres actions depuis l'interface web (ou du moins ces actions sont en attente dans la "file" de la socket réseau (maximum 5 actions) et sont exécutées ensuite). Je chercherais une solution à ce problème par la suite.

Gros pavé, mais n'hésite surtout pas si tu as des questions ! 👍

**Comment by baptistebisson** [comment]
Pas mal du tout ! 👍 
J'ai pu tester, la création marche bien mais aucun retour de ton script. Ça me met : 

> Json envoyee : {}

J'ai fais mon test sur une VM de 7mo histoire de pas perdre de temps, donc logiquement je devrais avoir un retour rapidement. La VM est bien créée derrière.
Par contre j'ai bien un retour quand j'ai une erreur.
Comment je vais gérer le délais côté utilisateur ? Sachant que j'attends maximum 7 secondes en socket avant de la fermer si je ne reçois pas de réponse.

**Comment by ChamMach** [comment]
Oui, c'est un "oubli" lorsque l'on choisi de créer une VM Windows 7. Je corrigerais cela lors du prochain push (le programme renverra bien un "true").
Pour le délais il n'est pas possible d'attendre 7 secondes pour le démarrage/l'arrêt d'une VM et de manière indéfinie pour la création (avec une condition par exemple) ? Quoiqu'il arrive le script renverra un résultat de toute manière. Donc pourquoi pas attendre uniquement son retour. Merci pour ton post !

**Comment by baptistebisson** [comment]
D'accord, parfait. Oui il faut toujours un retour.
Je pense que j'ai moyen de gérer ça. En fait j'avais rajouté le délais car je faisais des test avec `netcat` et quand je renvoyais rien, ça tournais sans fin et j'avais pas de notification vu que je n'avais aucun retour.

Ce que je peux faire c'est : 
- Délais de 7 secondes max pour les commandes rapide comme démarrage/arrêt
- Aucun délai pour la création

Par contre il faut gérer le délai de l'utilisateur. Il va pas attendre 7 minutes avec un loader. Si aucun retour pourquoi pas mettre une alerte box au dessus des filtres disans : 

> Demande création VM à tel date

**Comment by ChamMach** [comment]
Yep ce serait parfait ! Et du coup mettre à jour cette alerte box avec le retour (ok, pas ok avec telle erreur etc). Bon, l'utilisateur ne pourra rien faire d'autre pendant ce temps (vu que la socket sera prise et que ses futures actions iront dans une files d'attentes). Mais, je vais voir ce que je pourrais faire pour contourner ce problème.

**Comment by ChamMach** [comment]
J'ajouterais aussi que tout est obligatoire (à indiquer) lorsque l'on demande une création de VM : 
create_vm,os,ram,cpu,sto,desc ...

**Comment by baptistebisson** [comment]
J'arrive toujours pas à savoir comment faire pour gérer ce délai.
Ce que je pensais faire c'est de créer en base la VM et la mettre en attente sur l'affichage. Mais si je fais un retour à l'utilisateur je pourrais pas avoir ta confirmation de création vu que je n'écoute plus la socket.

Ton script envoyait `true` uniquement à la fin des 7mins ? Ca serait con de bloquer ma requête ajax sans retour pendant 7mins.

Peut-être qu'il faudrait rajouter un champ à ton retour JSON de `{ infos_vm: all }` vu que j'ai mon script qui tourne toutes les minutes. Comme ça si j'ai par exemple un champ en plus dans la VM du style `{ creation: true }` je pourrais actualiser ma page et enlever l'infobox ?

Dans tous les cas il faudrait que je prenne le manque de retour de la commande création par : 
- C'est bon tu peux mettre en base la VM et attendre mon retour dans infos_vm

Parce que si je n'ai pas de retour c'est que logiquement tout va bien ?

**Comment by ChamMach** [comment]
Mon script envoie un ```true``` quand la VM est créée, cela peut prendre 7 secondes comme 7 minutes (le temps du clonage). 
```{ infos_vm: all }``` renvoie toutes les VMs créées donc je ne comprends pas pourquoi il devrait y avoir un champ ```{ creation: true }```.  Le manque d'infos ne signifie pas que tout va bien ou que tout va mal. Cela signifie que le processus de création est lancé, le script renverra systématiquement quelque chose après cela.

Je pense que le mieux au lieu de ce prendre la tête est de matérialiser cette "file d'attente" en bdd. Créer une table, contenant un champ id (l'id de l'action (créer, démarrer, etc), l'id utilisateur, et le n° en file d'attente allant de 1 à 5 (puis pourquoi pas d'autres champs utiles si besoin).
Cela permettrais à ce que lorsqu'un utilisateur (quel qu'il soit) crée une action (créer une vm, démarrer une, etc), celle-ci soit inscrite en base en même temps d'être envoyé au script python. Et que, lorsque le nombre d'action = 5 alors on bloque toute possibilité d'action à tout les utilisateurs (en grisant les actions et en indiquant que 5 actions sont déjà en cours sur l'infrastructure). Puis pourquoi pas aussi que lorsqu'un utilisateur à la possibilité de faire une action (nb d'action en base < 5) alors indiquer son numéro en file d'attente lorsque l'action est créée (numéro qui se décrémente à chaque fin d'une action évidemment). 

Sinon, je pense que malheureusement pour cette version on devra attendre les 7mins (ou plus) le temps du clonage de la VM.

**Comment by baptistebisson** [comment]
C'est chiant ça. Du coup toutes mes commandes ajax ne feront que des modifs en base et ça sera le boulot d'un autre script de gérer les commandes vers ton script.

Bah non du coup la commande vers ton script sera exécuté plus tard du coup. Ca va être galère niveau PHP sinon, autant tout centraliser dans un script. Sauf qu'il devra s’exécuter toutes les secondes presque : 

- Regarder la table `queue`
- Prendre la première ligne et prendre les données en référence de la table VM
- Exécuter la commande vers ton script

Après le problème c'est les notifications utilisateurs, il faudrait une requête ajax toutes les secondes vers mon serveur pour savoir si l'action a été réalisée.

Je pense que tout ça est trop compliqué pour la MVP2. Autant continuer le système actuel. De toute manière ton script gère lui même la file d'attente déjà.
Je préfère me concentrer  sur ce qui est déjà fait plutôt que de partir trop loin sans avancer sur le reste.

**Comment by ChamMach** [comment]
Ça tient la route, inutile de se prendre la tête donc. L'utilisateur attendra avant que son action de création ne soit réalisée 👍

**Comment by baptistebisson** [comment]
Ta fait une erreur dans ton retour JSON : 
`{"create_vm": "false_modifyvmfailed"}`
Alors que tu m'as écrit ici : `{"create_vm": "false_modifyfailed"}`

Et quand j'ai ce message la VM se créée en plus.

**Comment by ChamMach** [comment]
Yep c'est bien une erreur, j'ai modifié le post. Le retour est bien ```{"create_vm": "false_modifyvmfailed"}```

Quand tu supprime une VM tu fais bien "clic droit => Supprimer" ? A-tu déjà créé une VM avec le même nom ? Si tu supprime et recrée la VM, tu as le même message ? Enfin, c'est systématique ou ce n'est juste que la première fois @baptistebisson ?

**Comment by ChamMach** [comment]
Plop, je viens de tester cette fonctionnalité. Quelques points à souligner : 

- La création d'une VM Centos ne fonctionne pas car dans le code json il est indiqué que l'os est "Centos": 

![image](https://user-images.githubusercontent.com/23166349/35236441-aade806a-ffa7-11e7-9aba-782b33825ffb.png)

Or, le code de l'OS est "RedHat_64". 

- La quantité de stockage par défaut est bien supportée, quel que soit le cas pour l'OS, mais ce n'est pas le cas pour la RAM et le CPU. 

- Pour finir avec une note positive, tout le reste est nickel et j’apprécie beaucoup les messages d'erreurs/success créés grâce au retour json du programme python. Bien joué ! 👍

**Comment by baptistebisson** [comment]
J'ai remplacé Centos par RedHat_64. https://github.com/ChamMach/VirtualWeb/commit/acca85985d09abbf724634ba6c19aba900df6354
Le min de ram était bien là mais il fallait cliquer sur le curseur avant qu'il ne s'actualise. J'ai corrigé ça.

Mais pas besoin pour le CPU vu que c'est toujours 1 le min.
