### ISSUE TITLE
Script VM - Partie modification d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#24]

**Comment by ChamMach** [comment]
Commit : 67e7b61
Fonctionnalité testée : Modification d'une VM

Code php employé : 
```
<?php require_once('D:\wamp64\www\virtualweb\shelpher.php');

$sockethelper = new sockethelper('192.168.1.12','1333');
$test = array(
    'modify_vm' => "1_Centos",
    'ram' => 2048,
    'cpu' => 2,
    'sto' => 35600,
    'desc' => 'Test modification');
$string = json_encode($test);

$sockethelper->send_data($string);

var_dump($sockethelper->read_data());

$sockethelper->close_socket();

?>
```
Le code php va interroger le programme python sur une action de modification des caractéristiques d'une VM. Une ou plusieurs caractéristiques (nom,ram,cpu,stockage,description) peuvent être modifiées (en ajoutant ou en enlevant des éléments de l'array php). Le stockage devra si possible être modifié à la hausse (et non à la baisse) donc prévoir cela dans le code php. Ces modifications nécessitent à ce que la VM cible soit **éteinte**.
Retour json de la fonction : 
- {"modify_vm":"true"} lorsque les modifications ont étés réalisées
- {"modify_vm":"false_vmdoesntexist"} lorsque la VM n'existe pas (ajouté aussi pour start_vm/stop_vm)
- {"modify_vm":"false_vmonline"} lorsque la VM est en ligne
- {"modify_vm":"false_vmstateunknown"} lorsque la VM dispose d'un statut inconnu (et donc est inutilisable)

N'hésite pas à me dire si tu as des questions @baptistebisson 👍

**Comment by baptistebisson** [comment]
Je n'arrive pas à modifier une VM

![](https://i.imgur.com/7awcFJt.png)

J'ai une erreur à la ligne 81. Je ne sais pas si ça vient de mon côté, j'ai essayé de mettre plus de ram, cpu, stockage pour être sûr mais pareil, ça crash ton exe

**Comment by ChamMach** [comment]
Ça viens du stockage. 6Mo de stockage c'est bien trop peu pour une VM. Surtout pour une modification, au risque de me répéter on ne peut pas diminuer le stockage alloué à une VM.

**Comment by baptistebisson** [comment]
Au risque de me répéter, j'ai dis que j'avais essayé de mettre plus de stockage, ex : 30 000 Mo

**Comment by ChamMach** [comment]
Oui mais par rapport à la VM qui a été créé si tu indique 30000 Mo on est toujours supérieur à la valeur originale ? Ça fonctionnait avant ou pas du tout ? Tu a mis à jour VirtualBox ? Quel est sa version ?
Étrange comme truc, je ne l'ai jamais eu

**Comment by baptistebisson** [comment]
30 000 est supérieur à 6 ? 🐰 
Jamais marché. Même avec les valeurs bien bien supérieure. Et je les vois bien dans ton retour console

**Comment by ChamMach** [comment]
Naaaan, si tu as créé une VM avec 50000Mo de stockage logique et que tu indique 30000Mo ceci explique cela. Et si tu ne change aucune valeur pour le stockage (que tu met le même nombre de Mo que ta VM dispose déjà) et que tu modifie les autres, ça fonctionne ? Tu sais que tu n'es pas obligé de tout envoyer aussi ? Tu peux par exemple uniquement modifier la ram etc

**Comment by baptistebisson** [comment]
Mais je suis pas con j'ai compris le principe qu'il faut demander plus de stockage et jamais moins.
J'ai 9,00 Mio de taille réelle et j'avais envoyé 30 000

Ah si j'avais réussi pour la description

**Comment by ChamMach** [comment]
30000 en taille logique, mais en taille logique ta VM a quelle valeur ?
Ok super, tu as quel version de VirtualBox ?

**Comment by baptistebisson** [comment]
![](https://i.imgur.com/SjXaMtP.png)

![](https://i.imgur.com/ql1bfXI.png)

**Comment by ChamMach** [comment]
Ok merci je crois savoir. Le mode de stockage est en "taille fixe" et non "taille dynamique". Un bug sous VirtualBox existe et comme on peut le voir ici, le stockage logique est inférieur au stockage réel (alors que normalement il devrait être égal pour du "taille fixe"). Je pense du coup que si tu recrée une VM en "taille dynamique" (avec par exemple 100Mo en taille dynamique) ça devrait fonctionner 👍

**Comment by ChamMach** [comment]
Quand je dis de recréer la VM je parle de la VM "template" Windows 7 utilisé (0_Windows7) et du coup aussi de créer une nouvelle VM à partir de ce template (1_jeaneude par exemple)

**Comment by baptistebisson** [comment]
Ça veut pas tant pis. Tu pourras essayer de ton côté et voir le retour python avec mon prochain commit quand tu auras le temps.

**Comment by ChamMach** [comment]
Arf.. Pas de soucis !
