### ISSUE TITLE
Script VM - Partie démarrage/arrêt d'une VM

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#25]
Definition of done : 

- [x] Démarrage : Démarrer une VM et envoyer un résultat en json
- [x] Arrêt : Arrêter une VM et envoyer un résultat en json

**Comment by ChamMach** [comment]
Commit : 6b803c4
Ajout des fonctions startvm et stopvm
Fonctionnalités testées : Démarrer/éteindre une VM

Start_vm, code php employé : 
```
<?php require_once('D:\wamp64\www\virtualweb\shelpher.php');

$sockethelper = new sockethelper('192.168.1.11','1333');
$test = array(
    'start_vm' => "1_Developpement");
$string = json_encode($test);

$sockethelper->send_data($string);

var_dump($sockethelper->read_data());

$sockethelper->close_socket();

?>
```
La code php interroge le programme python sur le démarrage de la vm "1_Developpement". Code retour en json du script : 

- {"start_vm": "true"} lorsque le démarrage de la VM a fonctionné => _Attente de 5 secondes (le temps que la VM s'allume) avant ce retour_
- {"start_vm": "false_vmalreadyonline"} lorsque la VM est déjà allumée
- {"start_vm": "false_sessionlocked"} lorsque la VM dispose de "session" (au sens virtualbox) inutilisable
- {"start_vm": "false_sessionunknown"} lorsque la VM dispose de "session" (au sens virtualbox) ayant un état inconnu et donc inutilisable
- {"start_vm": "false_startfailed"} lorsque la VM a échoué à démarrer
- {"start_vm": "false_statevmunknown"} lorsque la VM dispose d'un état inconnu et donc empêche le démarrage de la VM

Stop_vm, code php employé : 
```
<?php require_once('D:\wamp64\www\virtualweb\shelpher.php');

$sockethelper = new sockethelper('192.168.1.11','1333');
$test = array(
    'stop_vm' => "1_Developpement");
$string = json_encode($test);

$sockethelper->send_data($string);

var_dump($sockethelper->read_data());

$sockethelper->close_socket();

?>
```
La code php interroge le programme python sur l'arrêt de la vm "1_Developpement". Code retour en json du script : 

- {"stop_vm": "true"} lorsque l'arrêt de la VM a fonctionné  => _Attente de 5 secondes (le temps que la VM s'éteigne) avant ce retour_
- {"stop_vm": "false_vmalreadyoff"} lorsque la VM est déjà éteinte
- {"stop_vm": "false_sessionlocked"} lorsque la VM dispose de "session" (au sens virtualbox) inutilisable
- {"stop_vm": "false_sessionunknown"} lorsque la VM dispose de "session" (au sens virtualbox) ayant un état inconnu et donc inutilisable
- {"stop_vm": "false_stopfailed"} lorsque la VM a échoué à l'arrêt
- {"stop_vm": "false_statevmunknown"} lorsque la VM dispose d'un état inconnu et donc empêche le démarrage de la VM

Qu'en penses-tu @baptistebisson ? Je pense qu'il faudrait qu'à chaque fois que ces fonctions sont appelées par le code php, mettre à jour la bdd (notamment la partie sur l'état de la VM) lorsque le retour json est "true". Notamment afin d'éviter des "actions" plus rapides que le rafraîchissement de la bdd et pouvant créer des problèmes.

**Comment by baptistebisson** [comment]
Ca me semble parfait ! Oui mais il faudra attendre les 5 secondes du coup. Il faudra que je gère ça avec un spinner pour faire patienter.
Je vais l'intégrer à mon code dès que possible

**Comment by ChamMach** [comment]
Script répondant à la DoD et test sur l'interface web OK. Clôture de l'issue.
