### ISSUE TITLE
Configurer le serveur web

### ISSUE THREAD

**Issue by ChamMach** [ChamMach/VirtualWeb#4]

**Comment by baptistebisson** [comment]
Besoins du serveur selon les recommandations de [Laravel ](https://laravel.com/docs/5.5/installation):  

- PHP >= 7.0.0
- OpenSSL PHP Extension
- PDO PHP Extension
- Mbstring PHP Extension
- Tokenizer PHP Extension
- XML PHP Extension

Il est aussi recommandé d'avoir `composer` et `NPM/nodejs` en dernière version
